### ISSUE TITLE
Todo: Create different modes

### ISSUE THREAD

**Issue by bsamm** [bsamm/start-a-venue#17]
- [ ] Create a mode/filter that allows the user to select a venue, then all of the "Next Venues" light up (@kastnerkyle idea)
- [ ] make a drive mode that actually should the fastest driving directions, instead of just lines
- [ ] filter by genre mode

**Comment by kastnerkyle** [comment]
I sent that link to you, but will put it here too. It shows how to use Python and the Google Maps API, you could precalculate or query the API each time

https://github.com/rhiever/Data-Analysis-and-Machine-Learning-Projects/tree/master/optimal-road-trip

Also if you wanted to get fancy you could analyse the optimality of the Artist roadtrips, or calculate minimum paths for people who wanted to see artists in the minimum amount of time or minimimum distance with no regard for time. That would be more work though, and might be really gnarly in JS. No clue on that. 

http://nbviewer.jupyter.org/url/norvig.com/ipython/TSP.ipynb
